language: c
env:
  - OPTIONS= GET_WIN=
  - OPTIONS="--host=i586-mingw32msvc --build=$(uname -m)-pc-linux-gnu --enable-shared --with-libcurl=./win" PKG_CONFIG_PATH=./win/lib/pkgconfig LDFLAGS="-L./win/lib" CPPFLAGS="-I./win/include" GET_WIN=true
  - OPTIONS=--disable-threads GET_WIN=
  - OPTIONS="--disable-threads --host=i586-mingw32msvc --build=$(uname -m)-pc-linux-gnu --enable-shared --with-libcurl=./win" PKG_CONFIG_PATH=./win/lib/pkgconfig LDFLAGS="-L./win/lib" CPPFLAGS="-I./win/include" GET_WIN=true
matrix:
  include:
    - env: OPTIONS= GET_WIN=
      compiler: clang
    - env: OPTIONS=--disable-threads GET_WIN=
      compiler: clang
before_script:
  - test "x$GET_WIN" = x || wget -O- http://neufeldserver.uwaterloo.ca/~apmasell/pandaseq-windeps.tar.bz2 | tar xj
  - ./autogen.sh
  - test "x$GET_WIN" = x || export CC=i586-mingw32msvc-gcc
script: "./configure $OPTIONS && make all && test x$GET_WIN = xtrue || make check"
notifications:
  on_success: never
  on_failure: change
